import Head from "next/head";
import { useRouter } from "next/router";
import ThreadDetails from "../../components/ThreadDetails/ThreadDetails.jsx";
import Appbar from "../../components/UI/Appbar.jsx";
import * as constants from "../../constants.js";

const Thread = () => {
  const router = useRouter();
  /**
   * Thread Details component fetches the details of the thread after the page is loaded,
   * for this to work it needs to know which thread's details it has to fetch, so the permalink parameter
   * which is passed in the route which is further passed to the thread component as a prop.
   * It also helps to generate unique route for each thread.
   * Since ThreadDetails is a class component, trying to use the useRouter hook here and sending the data as prop
   */

  let link = router.query.threadId
    ?.split(constants.DYNAMIC_ROUTE_CONCAT_VALUE)
    ?.join("/");

  return (
    <>
      <Head>
        <title>Reddit/DotA2 | Thread</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Appbar />
      <ThreadDetails threadLink={link} />
    </>
  );
};

export default Thread;
