import Head from "next/head";
import SubReddit from "../components/SubReddit/SubReddit.jsx";
import Appbar from "../components/UI/Appbar.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Reddit/DotA2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Appbar />
      <SubReddit />
    </>
  );
}
